### ISSUE TITLE
libclang.so version

### ISSUE THREAD

**Issue by exuvo** [jsoysouvanh/Kodgen#3]
Why do you include a version of libclang.so instead of just using the system installed version? With the included one i just get linking errors as i have newer versions of the other dynamic libraries libclang.so depends on.

**Comment by jsoysouvanh** [comment]
I did that so the repository is ready to build and any user can just compile and it works without having to care for dependencies. It also allows me to target a minimum version of clang that the user might not fulfill on their machine. 

Ideally we should use a package manager but I didn't find any solution to fetch only libclang.

Of course, if you have a more recent version of clang and you want to use it, you can!

**Comment by exuvo** [comment]
Okay i'll keep linking mine to the system libclang then. I'm also having problems with the new v2 refureku but i will open another issue for that tomorrow.
